# controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 50

# ---------------------------
# Joint State Controller
# ---------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# ---------------------------
# Steering Servo Controllers
# ---------------------------
front_left_steering_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_steering_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }

front_right_steering_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_steering_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }

rear_left_steering_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_steering_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }

rear_right_steering_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_steering_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }

# ---------------------------
# Drive Motors (Continuous)
# ---------------------------
front_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }

front_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }

middle_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: middle_left_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }

middle_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: middle_right_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }

rear_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_left_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }

rear_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_right_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }

# ---------------------------
# 5-DOF Arm Joint Controllers
# ---------------------------
shoulder_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_joint
  pid: { p: 30.0, i: 0.0, d: 1.0 }

upper_arm_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: upper_arm_joint
  pid: { p: 30.0, i: 0.0, d: 1.0 }

forearm_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: forearm_joint
  pid: { p: 30.0, i: 0.0, d: 1.0 }

wrist_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_pitch_joint
  pid: { p: 30.0, i: 0.0, d: 1.0 }

wrist_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_roll_joint
  pid: { p: 5.0, i: 0.0, d: 0.2 }
