controller_manager:
  ros__parameters:
    update_rate: 50
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
fl_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: fl_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }
ml_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: ml_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }
rl_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rl_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }
fr_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: fr_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }
mr_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: mr_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }
rr_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rr_wheel_joint
  pid: { p: 8.0, i: 0.0, d: 0.2 }
fl_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: fl_steer_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }
fr_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: fr_steer_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }
rl_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: rl_steer_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }
rr_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: rr_steer_joint
  pid: { p: 20.0, i: 0.0, d: 1.0 }
arm_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1: {p: 100.0, d: 1.0, i: 0.0}
    arm_joint_2: {p: 100.0, d: 1.0, i: 0.0}
    arm_joint_3: {p: 80.0, d: 0.8, i: 0.0}
    arm_joint_4: {p: 60.0, d: 0.6, i: 0.0}
    arm_joint_5: {p: 20.0, d: 0.2, i: 0.0}
  state_publish_rate: 50
  action_monitor_rate: 10
