ekf_filter_node:
  frequency: 50
  two_d_mode: true
  sensor_timeout: 0.1
  print_diagnostics: true
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: /odom
  odom0_config: [true, true, false, false, false, false, false, false, false, false, false, false]

  imu0: /imu/data
  imu0_config: [false, false, false, true, true, true, false, false, false, false, false, false]

  use_control: false
