base_global_planner: navfn/NavfnROS
base_local_planner: dwa_local_planner/DWAPlannerROS
planner_frequency: 5.0

DWAPlannerROS:
  max_vel_x: 0.6
  min_vel_x: -0.2
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: -1.0
  sim_time: 1.5
  vx_samples: 6
  vtheta_samples: 20
